### ISSUE TITLE
A number divided by infinity results in zero, not infinity. Noted by a student in AMS class 31.

### ISSUE THREAD

**Issue by remarcmij** [HackYourFutureBelgium/debugging#4]
https://github.com/HackYourFutureBelgium/debugging/blob/5bc31f1b1f7543adc0d72b6bbbc86471853b8109/isolate/11-arithmetic/examples/3-edge-cases.js#L68

**Comment by colevandersWands** [comment]
thanks for the heads-up @remarcmij.  I missed your issue but Rob let me know on slack.  I think [this](https://github.com/HackYourFutureBelgium/debugging/blob/b4cf3716c65199293680d425b0329c39e9cf0298/isolate/11-arithmetic/examples/3-edge-cases.js#L68) fixes it
